# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_element', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treeelement',
            options={'verbose_name': 'Tree element', 'verbose_name_plural': 'Tree elements'},
        ),
    ]
