# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_element', '0002_auto_20170721_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeelement',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treeelement',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
