# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20170731_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='root_folders',
            field=models.ManyToManyField(related_name='menus', related_query_name='menu', to='tree_element.TreeElement'),
        ),
    ]
